"""RENAME_ME

Revision ID: 70b51c6758b2
Revises: 94d1f4d9ef32
Create Date: 2025-10-17 16:33:30.691427

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "71b51c6758b2"
down_revision: Union[str, None] = "70b51c6758b2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        DELETE FROM processingtask WHERE status not in ("failed", "completed", "pending", "running", "cancelled")
    """
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
